[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spectroSLEUTH"
version = "0.0.2"

dependencies = [
 "numpy",
 "matplotlib", 
 "pandas", 
 "astropy", 
 "scipy"
]

